### ISSUE TITLE
Missing contact form?

### ISSUE THREAD

**Issue by garethredfern** [wjgilmore/todoparrot#2]
Hi Jason, is it me or is the`resources/views/about/contact.blade.php` missing as per P140 of your book?

**Comment by garethredfern** [comment]
Sorry just realised this is the project at the start, it would be nice if there was a "completed" branch too?

**Comment by wjgilmore** [comment]
You should definitely see most of the components discussed in book, including models, controllers, seeds, etc. However you are right I did not merge in the contact form, will try to do that later today. Sorry about that!

**Comment by wjgilmore** [comment]
Better late than never? :-) All of the necessary code is now found in the repo.
