### ISSUE TITLE
A better way to do the slugging (sure is better)

### ISSUE THREAD

**Issue by unclepickles** [wjgilmore/todoparrot#7]
Hi there
I have had problems using the package Cviebrock\EloquentSluggable
Problems start when you try to incorporate it, the book says to add:
'Cviebrock\EloquentSluggable\SluggableServiceProvider', to the providers.
However using 5.1 they use ::class in every line, that's prolly alright with 5,0 but it took sometime to implement it on 5.1 (I actually added ::class and it worked)
However when I did the 'implement' step, I know from my Java programming background that you should implement all the methods the interface has in order to use the class, phpstorm complained about it, but still I managed to do the trick in 5.0 and it created a column in the database and it worked sluggifying each entry into it.
However in page 100 you find that you need 5.1 (for sake of using the faker factory) so I abandoned project straightaway and did a fresh 5.1 installation.

Now, there it simply refused to budge and all stopped working, so I came up with this neat solution.

First here's the method to track back on the last steps.

1- First remove the published vendor by deleting the files copied by composer, 
2- then remove the $sluggable variable from the Todolist class.
3- then remove the migration file ... (had to adjust the autoload.php file otherwise couldn't delete it)
4- then I removed the provider from config/app.php
5- then I removed the slug column from the database.
6- then I removed the entry from composer.json
7- then did composer update to adjust everything, now this package has been wiped out.

To do it my way 
1- Create a migration file to add the slug column
2- then migrate to get your table adjusted, then simply use tinker to

>>> foreach($lists as $list) {
... $list->slug = str_slug($list->name, "-");
... $list->save();
... }
=> null
>>>

the table has been populated with just use the str_slug helper function to get your reward as above.

I hope this helps other uses

**Comment by wjgilmore** [comment]
This has all been cleaned up nicely in Laravel 5.1 and beyond. Thanks for the useful instructions @unclepickles!
