### ISSUE TITLE
route:list error

### ISSUE THREAD

**Issue by sembrex** [wjgilmore/todoparrot#9]
I'm a new comer to laravel. start learning it 2 days ago. i've installed TODOParrot on my machine and it run as on your website
I found an error when trying to get list of routes.
'namespace' => 'admin' in routes.php causing that error. PHP os case sensitive, isn't it?
'Admin' folder inside Controllers writen with capital 'A'

**Comment by sembrex** [comment]
sorry for my bad english :)

**Comment by shk33** [comment]
Yes, Php is case sensitive

**Comment by RodrigoJimmy** [comment]
What error?
